### PR TITLE
Use Spring dependency management

### PR DESCRIPTION
**Pull request by Kantis**
I think it's best practice to let Spring manage its dependencies, otherwise you can end up in a state where you have too new/old versions of something in the tree and it gets messy easily. 😄

### CODE REVIEW

**Comment by sksamuel** [comment]
Are the kotlinx-coroutines-reactor handled by spring too ?

**Comment by Kantis** [comment]
Yup 🙂

**Comment by Kantis** [comment]
Here's the full list of managed dependencies. https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html

Even Kotlin version seem to be decided by the plug-in 😅

**Comment by sksamuel** [comment]
Ok just need to fix conflict then looks good.

**Pull request merged**
